//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO
    {
        public int Id_Evento { get; set; }
        public string Tipo_evento { get; set; }
        public System.DateTime FechaEvento { get; set; }
        public System.TimeSpan HoraRealización { get; set; }
        public Nullable<int> Id_Arrendatario { get; set; }
        public Nullable<int> Id_Encargado { get; set; }
        public Nullable<int> Id_Precio { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> Id_lugar { get; set; }
    
        public virtual ENCARGADO ENCARGADO { get; set; }
        public virtual TIPO_PRESENTACION TIPO_PRESENTACION { get; set; }
        public virtual PRECIOS_EVENTOS PRECIOS_EVENTOS { get; set; }
        public virtual LUGAR LUGAR { get; set; }
    }
}
