//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO_ARTISTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GRUPO_ARTISTA()
        {
            this.TIPO_PRESENTACION = new HashSet<TIPO_PRESENTACION>();
        }
    
        public int Id_grupoArtista { get; set; }
        public string Nombre { get; set; }
        public string Nacionalidad { get; set; }
        public string COMENTARIOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIPO_PRESENTACION> TIPO_PRESENTACION { get; set; }
    }
}
