//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerProyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEventosEntities : DbContext
    {
        public DBEventosEntities()
            : base("name=DBEventosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DISTRITO> DISTRITO { get; set; }
        public virtual DbSet<ENCARGADO> ENCARGADO { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<GRUPO_ARTISTA> GRUPO_ARTISTA { get; set; }
        public virtual DbSet<LUGAR> LUGAR { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<PRECIOS_EVENTOS> PRECIOS_EVENTOS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIPO_PRESENTACION> TIPO_PRESENTACION { get; set; }
    }
}
