//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerProyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PRESENTACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PRESENTACION()
        {
            this.EVENTO = new HashSet<EVENTO>();
        }
    
        public int Id_Presentacion { get; set; }
        public string Nombre_Presentacion { get; set; }
        public int Telefono { get; set; }
        public int Personas_Evento { get; set; }
        public Nullable<int> Id_grupoArtista { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTO> EVENTO { get; set; }
        public virtual GRUPO_ARTISTA GRUPO_ARTISTA { get; set; }
    }
}
